### ISSUE TITLE
KAFKA_BROKERCONNECT FQDN is being shortened

### ISSUE THREAD

**Issue by agapic** [obsidiandynamics/kafdrop#105]
So I'm trying to connect to our Kafka brokers which live on, say, `andrew.dev.myvpn.com:9091`. 

Everything appears to start up correctly when running the docker container. Then when I navigate to localhost, I get the following flurry of exceptions (below). In the docker container, when I ping `andrew.dev.myvpn.com` I get responses. When I ping `andrew` I don't. Is kafdrop truncating the FQDN (andrew.dev.myvpn.com) to andrew in the application code? If so, is there a way to either: fix that in kafdrop, or get around it somehow using docker-fu?

```
2020-04-09 23:02:38.331  WARN 13 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Error connecting to node andrew:9091 (id: 3 rack: null)

java.net.UnknownHostException: andrew
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at org.apache.kafka.clients.ClientUtils.resolve(ClientUtils.java:104)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.currentAddress(ClusterConnectionStates.java:403)
	at org.apache.kafka.clients.ClusterConnectionStates$NodeConnectionState.access$200(ClusterConnectionStates.java:363)
	at org.apache.kafka.clients.ClusterConnectionStates.currentAddress(ClusterConnectionStates.java:151)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:943)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:288)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:925)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1140)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by agapic** [comment]
I think the host without the FQDN is from the advertised listeners. Still not sure how to get docker to connect to it though :(
