### ISSUE TITLE
kafdrop sasl protocol connection issue

### ISSUE THREAD

**Issue by varun-tangoit** [obsidiandynamics/kafdrop#209]
Hi,

Im trying to connect with kafka broker with security procol as SASL and mechanism - PLAIN, i have configured jass config also, but still i got address not available not able to connect with kafka server. can you help me out from this issue, here i have mentioned logs;

```
[2020-11-07 13:18:42,019] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka_1    | java.lang.IllegalArgumentException: requirement failed: Each listener must have a different name, listeners: EXTERNAL://xxx:9092,EXTERNAL://xxx:29092
kafka_1    | 	at scala.Predef$.require(Predef.scala:281)
kafka_1    | 	at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:306)
kafka_1    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:316)
kafka_1    | 	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1407)
kafka_1    | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1482)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
kafka_1    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
kafka_1    | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1    | 	at kafka.Kafka$.main(Kafka.scala:68)
kafka_1    | 	at kafka.Kafka.main(Kafka.scala)
[2020-11-07 13:19:07,857] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka_1    | [2020-11-07 13:19:08,840] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka_1    | java.lang.IllegalArgumentException: requirement failed: Each listener must have a different name, listeners: EXTERNAL://xxx:9092,EXTERNAL://xxx:29092
kafka_1    | 	at scala.Predef$.require(Predef.scala:281)
kafka_1    | 	at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:306)
kafka_1    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:316)
kafka_1    | 	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1407)
kafka_1    | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1482)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
kafka_1    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
kafka_1    | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1    | 	at kafka.Kafka$.main(Kafka.scala:68)
kafka_1    | 	at kafka.Kafka.main(Kafka.scala)
kafka_1    | Kafka exited with code 1; restarting in 5 seconds... (attempts remaining: 6)
kafka_1    | [2020-11-07 13:19:15,295] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka_1    | [2020-11-07 13:19:16,308] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka_1    | java.lang.IllegalArgumentException: requirement failed: Each listener must have a different name, listeners: EXTERNAL://xxx:9092,EXTERNAL://xxx:29092
kafka_1    | 	at scala.Predef$.require(Predef.scala:281)
kafka_1    | 	at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:306)
kafka_1    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:316)
kafka_1    | 	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1407)
kafka_1    | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1482)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
kafka_1    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
kafka_1    | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1    | 	at kafka.Kafka$.main(Kafka.scala:68)
kafka_1    | 	at kafka.Kafka.main(Kafka.scala)
kafka_1    | Kafka exited with code 1; restarting in 5 seconds... (attempts remaining: 5)
kafka_1    | [2020-11-07 13:19:23,172] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka_1    | [2020-11-07 13:19:24,312] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka_1    | java.lang.IllegalArgumentException: requirement failed: Each listener must have a different name, listeners: EXTERNAL://xxx:9092,EXTERNAL://xxx:29092
kafka_1    | 	at scala.Predef$.require(Predef.scala:281)
kafka_1    | 	at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:306)
kafka_1    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:316)
kafka_1    | 	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1407)
kafka_1    | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1482)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
kafka_1    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
kafka_1    | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1    | 	at kafka.Kafka$.main(Kafka.scala:68)
kafka_1    | 	at kafka.Kafka.main(Kafka.scala)
kafka_1    | Kafka exited with code 1; restarting in 5 seconds... (attempts remaining: 4)
kafka_1    | [2020-11-07 13:19:30,983] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
kafka_1    | [2020-11-07 13:19:31,988] ERROR Exiting Kafka due to fatal exception (kafka.Kafka$)
kafka_1    | java.lang.IllegalArgumentException: requirement failed: Each listener must have a different name, listeners: EXTERNAL://xxx:9092,EXTERNAL://xxx:29092
kafka_1    | 	at scala.Predef$.require(Predef.scala:281)
kafka_1    | 	at kafka.utils.CoreUtils$.validate$1(CoreUtils.scala:306)
kafka_1    | 	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:316)
kafka_1    | 	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1407)
kafka_1    | 	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1482)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1460)
kafka_1    | 	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1114)
kafka_1    | 	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1094)
kafka_1    | 	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
kafka_1    | 	at kafka.Kafka$.main(Kafka.scala:68)
kafka_1    | 	at kafka.Kafka.main(Kafka.scala)

```

**Comment by varun-tangoit** [comment]
Hi, Anyone help me out from this issue, please give me any suggestion regarding this issue

**Comment by yuzhichang** [comment]
@varun-tangoit Are kafka builtin utils (kafka-consumer-groups.sh, kafka-console-producer.sh, kafka-console-consumer.sh) able to auth to Kafka?
