### ISSUE TITLE
Kafdrop times out, if any broker node is down

### ISSUE THREAD

**Issue by jpuris** [obsidiandynamics/kafdrop#210]
Kafdrop version 3.27.0, pulled from docker hub obsidiandynamics/kafdrop:3.27.0

**Steps to reproduce**
1. Have running Kafdrop instance 
2. Have running Kafka cluster
3. Stop one of the nodes in kafka cluster

**Expected**
- Kafdrop instance accessible and show tone of the cluster nodes unavailable

**What happens instead**
- Kafdrop instance becomes unavailable
- Kafdrop instance barrages the stdout with same log lines and eventual timeout reached

**Environment**
_Kafka cluster nodes_
- ms-vg-kafka-01.mnw.no (is deliberately shut down)
- ms-vg-kafka-02.mnw.no
- ms-vg-kafka-03.mnw.no

**Logs from Kafdrop container**
```
2020-11-09 15:58:31.383  WARN 1 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Connection to node 1 (ms-vg-kafka-01.mnw.no/172.25.73.191:9093) could not be established. Broker may not be available.
2020-11-09 16:04:12.644  WARN 1 [  XNIO-1 task-4] o.a.k.c.NetworkClient                    : [Consumer clientId=kafdrop-consumer, groupId=null] Connection to node 1 (ms-vg-kafka-01.mnw.no/172.25.73.191:9093) could not be established. Broker may not be available.
2020-11-09 16:04:13.130  WARN 1 [  XNIO-1 task-4] k.c.NetworkClient$DefaultMetadataUpdater : [Consumer clientId=kafdrop-consumer, groupId=null] 16 partitions have leader brokers without a matching listener, including [__consumer_offsets-20, __consumer_offsets-11, __consumer_offsets-32, __consumer_offsets-8, __consumer_offsets-29, __consumer_offsets-41, __consumer_offsets-5, __consumer_offsets-35, __consumer_offsets-26, __consumer_offsets-44]
[..]
2020-11-09 16:05:13.342 ERROR 1 [  XNIO-1 task-4] i.u.s.a.LoggingExceptionHandler          : UT005023: Exception handling request to /

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition __consumer_offsets-17 could be determined
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at kafdrop.config.CorsConfiguration$1.doFilter(CorsConfiguration.java:88)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition __consumer_offsets-17 could be determined

errorAtts: {timestamp=Mon Nov 09 16:05:13 GMT 2020, status=500, error=Internal Server Error, message=Request processing failed; nested exception is org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition __consumer_offsets-17 could be determined, trace=org.apache.kafka.common.errors.TimeoutException: Timeout of 60000ms expired before the position for partition __consumer_offsets-17 could be determined
, path=/}
```

Following log message repeats many times a second for about a minute. The barrage of log is triggered when kafdrop URL is opened in web browser
```
k.c.NetworkClient$DefaultMetadataUpdater : [Consumer clientId=kafdrop-consumer, groupId=null] 16 partitions have leader brokers without a matching listener, including [__consumer_offsets-20, __consumer_offsets-11, __consumer_offsets-32, __consumer_offsets-8, __consumer_offsets-29, __consumer_offsets-41, __consumer_offsets-5, __consumer_offsets-35, __consumer_offsets-26, __consumer_offsets-44]
```

Other tools, producers and consumers seem to not have an issue with 1/3 kafka cluster nodes down. Here is output of `kafkacat`
```
❯ kafkacat -b ms-vg-kafka-01.mnw.no:9093,ms-vg-kafka-02.mnw.no:9093,ms-vg-kafka-03.mnw.no:9093 -X security.protocol=ssl -L
%3|1604940248.196|FAIL|rdkafka#producer-1| [thrd:ssl://ms-vg-kafka-01.mnw.no:9093/bootstrap]: ssl://ms-vg-kafka-01.mnw.no:9093/bootstrap: Connect to ipv4#172.25.73.191:9093 failed: Connection refused (after 9ms in state CONNECT)
Metadata for all topics (from broker 3: ssl://ms-vg-kafka-03.mnw.no:9093/3):
 2 brokers:
  broker 2 at ms-vg-kafka-02.mnw.no:9093
  broker 3 at ms-vg-kafka-03.mnw.no:9093 (controller)
 9 topics:
  topic "__transaction_state" with 50 partitions:
    partition 0, leader 3, replicas: 3, isrs: 3
    partition 1, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 2, leader 2, replicas: 2, isrs: 2
    partition 3, leader 3, replicas: 3, isrs: 3
    partition 4, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 5, leader 2, replicas: 2, isrs: 2
    partition 6, leader 3, replicas: 3, isrs: 3
    partition 7, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 8, leader 2, replicas: 2, isrs: 2
    partition 9, leader 3, replicas: 3, isrs: 3
    partition 10, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 11, leader 2, replicas: 2, isrs: 2
    partition 12, leader 3, replicas: 3, isrs: 3
    partition 13, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 14, leader 2, replicas: 2, isrs: 2
    partition 15, leader 3, replicas: 3, isrs: 3
    partition 16, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 17, leader 2, replicas: 2, isrs: 2
    partition 18, leader 3, replicas: 3, isrs: 3
    partition 19, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 20, leader 2, replicas: 2, isrs: 2
    partition 21, leader 3, replicas: 3, isrs: 3
    partition 22, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 23, leader 2, replicas: 2, isrs: 2
    partition 24, leader 3, replicas: 3, isrs: 3
    partition 25, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 26, leader 2, replicas: 2, isrs: 2
    partition 27, leader 3, replicas: 3, isrs: 3
    partition 28, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 29, leader 2, replicas: 2, isrs: 2
    partition 30, leader 3, replicas: 3, isrs: 3
    partition 31, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 32, leader 2, replicas: 2, isrs: 2
    partition 33, leader 3, replicas: 3, isrs: 3
    partition 34, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 35, leader 2, replicas: 2, isrs: 2
    partition 36, leader 3, replicas: 3, isrs: 3
    partition 37, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 38, leader 2, replicas: 2, isrs: 2
    partition 39, leader 3, replicas: 3, isrs: 3
    partition 40, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 41, leader 2, replicas: 2, isrs: 2
    partition 42, leader 3, replicas: 3, isrs: 3
    partition 43, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 44, leader 2, replicas: 2, isrs: 2
    partition 45, leader 3, replicas: 3, isrs: 3
    partition 46, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 47, leader 2, replicas: 2, isrs: 2
    partition 48, leader 3, replicas: 3, isrs: 3
    partition 49, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
  topic "default_ksql_processing_log" with 1 partitions:
    partition 0, leader 2, replicas: 2, isrs: 2
  topic "_schemas" with 1 partitions:
    partition 0, leader 2, replicas: 1,2,3, isrs: 3,2
  topic "_confluent-ksql-default__command_topic" with 1 partitions:
    partition 0, leader 3, replicas: 1,3,2, isrs: 3,2
  topic "jp_test" with 3 partitions:
    partition 0, leader 3, replicas: 3,1,2, isrs: 3,2
    partition 1, leader 2, replicas: 1,2,3, isrs: 2,3
    partition 2, leader 2, replicas: 2,3,1, isrs: 2,3
  topic "__consumer_offsets" with 50 partitions:
    partition 0, leader 2, replicas: 2, isrs: 2
    partition 1, leader 3, replicas: 3, isrs: 3
    partition 2, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 3, leader 2, replicas: 2, isrs: 2
    partition 4, leader 3, replicas: 3, isrs: 3
    partition 5, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 6, leader 2, replicas: 2, isrs: 2
    partition 7, leader 3, replicas: 3, isrs: 3
    partition 8, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 9, leader 2, replicas: 2, isrs: 2
    partition 10, leader 3, replicas: 3, isrs: 3
    partition 11, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 12, leader 2, replicas: 2, isrs: 2
    partition 13, leader 3, replicas: 3, isrs: 3
    partition 14, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 15, leader 2, replicas: 2, isrs: 2
    partition 16, leader 3, replicas: 3, isrs: 3
    partition 17, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 18, leader 2, replicas: 2, isrs: 2
    partition 19, leader 3, replicas: 3, isrs: 3
    partition 20, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 21, leader 2, replicas: 2, isrs: 2
    partition 22, leader 3, replicas: 3, isrs: 3
    partition 23, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 24, leader 2, replicas: 2, isrs: 2
    partition 25, leader 3, replicas: 3, isrs: 3
    partition 26, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 27, leader 2, replicas: 2, isrs: 2
    partition 28, leader 3, replicas: 3, isrs: 3
    partition 29, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 30, leader 2, replicas: 2, isrs: 2
    partition 31, leader 3, replicas: 3, isrs: 3
    partition 32, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 33, leader 2, replicas: 2, isrs: 2
    partition 34, leader 3, replicas: 3, isrs: 3
    partition 35, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 36, leader 2, replicas: 2, isrs: 2
    partition 37, leader 3, replicas: 3, isrs: 3
    partition 38, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 39, leader 2, replicas: 2, isrs: 2
    partition 40, leader 3, replicas: 3, isrs: 3
    partition 41, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 42, leader 2, replicas: 2, isrs: 2
    partition 43, leader 3, replicas: 3, isrs: 3
    partition 44, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 45, leader 2, replicas: 2, isrs: 2
    partition 46, leader 3, replicas: 3, isrs: 3
    partition 47, leader -1, replicas: 1, isrs: 1, Broker: Leader not available
    partition 48, leader 2, replicas: 2, isrs: 2
    partition 49, leader 3, replicas: 3, isrs: 3
  topic "_connect-offsets" with 3 partitions:
    partition 0, leader 2, replicas: 2,1,3, isrs: 3,2
    partition 1, leader 3, replicas: 3,2,1, isrs: 3,2
    partition 2, leader 3, replicas: 1,3,2, isrs: 3,2
  topic "_connect-status" with 3 partitions:
    partition 0, leader 3, replicas: 3,1,2, isrs: 3,2
    partition 1, leader 2, replicas: 1,2,3, isrs: 3,2
    partition 2, leader 3, replicas: 2,3,1, isrs: 3,2
  topic "_connect-configs" with 1 partitions:
    partition 0, leader 3, replicas: 1,3,2, isrs: 3,2
```

Kafkadrop k8s container spec
```yaml
    spec:
      containers:
      - name: kafdrop
        image: obsidiandynamics/kafdrop:3.27.0
        ports:
        - containerPort: 9000
        env:
          - name: KAFKA_BROKERCONNECT
            value: "ms-vg-kafka-01.mnw.no:9093,ms-vg-kafka-02.mnw.no:9093,ms-vg-kafka-03.mnw.no:9093"
          - name: SCHEMAREGISTRY_CONNECT
            value: "ms-kafka-schema.mnw.no:443"
          - name: JVM_OPTS
            value: "-Xms480M -Xmx480M"
          - name: SERVER_PORT
            value: "9000"
          - name: SERVER_SERVLET_CONTEXTPATH
            value: "/"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
```

**Comment by jpuris** [comment]
Forgot to mention. When the shut down node is online again, Kafdrop resumes normal operation without restart of container or any other intervention, which is nice.

**Comment by eswardpm** [comment]
just to add, I get the exact same issue with __consumer_offset topic access issue. I have user that has admin privilege on a cluster, when I try to connect to that cluster I dont see this issue. But when I try to connect to a cluster in which my user has only access to  5 topics. In that case when i try to view the message on those 5 topics then I run into this timeout error specific to "__consumer_offset" topic.

**Comment by baganokodo** [comment]
Exact the same issue happened when CruiseControl was executing a cluster-wide rebalancing.
