### ISSUE TITLE
Protobuf message deserialization failure

### ISSUE THREAD

**Issue by Omega359** [obsidiandynamics/kafdrop#247]
I've been setting up a kafka based event system and I thought to use kafdrop for other to easily view and manage topics. However I've had issues when trying to get the obsidiandynamics/kafdrop docker image to actually view messages in a topic. kafdrop is configured via:
```
kafka-ui:
    image: obsidiandynamics/kafdrop
    container_name: kafka-ui
    hostname: kafka-ui
    restart: always
    environment:
      JVM_OPTS: "-Xms32M -Xmx128M"
      KAFKA_BROKERCONNECT: 'kafka:29092'
      SERVLET_SERVLET_CONTEXTPATH: "/"
      CMD_ARGS: "--message.format=PROTOBUF --protobufdesc.directory=/var/protobuf_desc"
    ports:
      - "9001:9000"    
    depends_on: 
      kafka:
        condition: service_healthy  
    volumes:
      - ${PROTOBUF_DESCRIPTOR_DIR}:/var/protobuf_desc
```
The protodesc files are generated via the 
```
<groupId>com.github.os72</groupId>
                <artifactId>protoc-jar-maven-plugin</artifactId>
                <version>3.11.4</version>
```
maven plugin with a 'descriptor' output target using protobuf 3.14.0

Kafdrop's UI correctly lists the protobuf descriptors however when selection the correct one for the channel and providing the proper message type name kafdrop produces the following stack trace:
```
Stack trace
kafdrop.util.DeserializationException: Can't decode Protobuf message at kafdrop.util.ProtobufMessageDeserializer.deserializeMessage(ProtobufMessageDeserializer.java:79) at kafdrop.service.KafkaHighLevelConsumer.deserialize(KafkaHighLevelConsumer.java:199) at kafdrop.service.KafkaHighLevelConsumer.lambda$getLatestRecords$3(KafkaHighLevelConsumer.java:132) at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1510) at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) at kafdrop.service.KafkaHighLevelConsumer.getLatestRecords(KafkaHighLevelConsumer.java:135) at kafdrop.service.KafkaMonitorImpl.getMessages(KafkaMonitorImpl.java:166) at 
...
```
The actual error listed in the logs for kafdrop is 
```
2021-03-06 22:06:40.971 ERROR 1 [ XNIO-1 task-8] k.u.ProtobufMessageDeserializer : Can't decode Protobuf message


com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).

at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:102)

at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:627)

at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:431)

at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:420)

at com.google.protobuf.DynamicMessage.parseFrom(DynamicMessage.java:92)

at kafdrop.util.ProtobufMessageDeserializer.deserializeMessage(ProtobufMessageDeserializer.java:66)

at kafdrop.service.KafkaHighLevelConsumer.deserialize(KafkaHighLevelConsumer.java:199)

at kafdrop.service.KafkaHighLevelConsumer.lambda$getLatestRecords$3(KafkaHighLevelConsumer.java:132)

at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)

at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1510)

at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)

at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)

at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)

at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)

at kafdrop.service.KafkaHighLevelConsumer.getLatestRecords(KafkaHighLevelConsumer.java:135)

at kafdrop.service.KafkaMonitorImpl.getMessages(KafkaMonitorImpl.java:166)

at kafdrop.service.MessageInspector.getMessages(MessageInspector.java:42)

at kafdrop.controller.MessageController.viewMessageForm(MessageController.java:172)
```

**Comment by Omega359** [comment]
I realized that the cause of this issue is because I'm not actually writing out just a protobuf byte array into the kafka topics but rather a custom format (I encode the classname into the bytes to make deserialization easy). However that does bring up a different issue - how to use a custom deserializer?
