### ISSUE TITLE
Docker use: Connecting to Broker through Corporate Network (How to turn off SSL Validation)

### ISSUE THREAD

**Issue by tolgabalci** [obsidiandynamics/kafdrop#264]
I have KafDrop working connecting to the Broker and Schema Registry, but it breaks with the below error if I connect to VPN and the traffic is inspected by the corporate firewall which does a man in the middle attack type of SSL inspection.

To get around this I normally have to turn off SSL validation.  How can I do this when I'm using KafDrop as a Docker container under Windows?

Alternatively I could get the certificate our firewall is using from the Windows Cert store, but not sure what to do with it after that.

```
Internal Server Error

A 500 error has occurred: Request processing failed; nested exception is org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 100587
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1324)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1199)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1146)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:441)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:419)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1180)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1091)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:187)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:330)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:208)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:252)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:482)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:475)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:153)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndId(CachedSchemaRegistryClient.java:232)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getById(CachedSchemaRegistryClient.java:211)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:116)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:88)
	at io.confluent.kafka.serializers.KafkaAvroDeserializer.deserialize(KafkaAvroDeserializer.java:55)
	at kafdrop.util.AvroMessageDeserializer.deserializeMessage(AvroMessageDeserializer.java:22)
	at kafdrop.service.KafkaHighLevelConsumer.deserialize(KafkaHighLevelConsumer.java:199)
	at kafdrop.service.KafkaHighLevelConsumer.lambda$getLatestRecords$3(KafkaHighLevelConsumer.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1510)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at kafdrop.service.KafkaHighLevelConsumer.getLatestRecords(KafkaHighLevelConsumer.java:135)
	at kafdrop.service.KafkaMonitorImpl.getMessages(KafkaMonitorImpl.java:166)
	at kafdrop.service.MessageInspector.getMessages(MessageInspector.java:42)
	at kafdrop.controller.MessageController.viewMessageForm(MessageController.java:172)
        ...
```

**Comment by lfmunoz** [comment]
Not an issue with kafkadrop. Likely go read JVM documentation on what property to set to ignore certificate validation.

Probably it is: 

-Dcom.sun.net.ssl.checkRevocation=false

reference: https://stackoverflow.com/questions/4663147/is-there-a-java-setting-for-disabling-certificate-validation

best to use the certificates. look here: https://github.com/obsidiandynamics/kafdrop/issues/201
