### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by haf** [obsidiandynamics/kafdrop#331]
Docs state it should be possible to configure like this (docker-compose)

```
  # https://github.com/obsidiandynamics/kafdrop
  # https://hub.docker.com/r/obsidiandynamics/kafdrop
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
    - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M" 
      SERVER_SERVLET_CONTEXTPATH: /
```

Gets you error:

```
run-mmm-kafdrop-1  | 2022-01-08 01:44:44.221  INFO ${sys:PID} [           main] k.Kafdrop$EnvironmentSetupListener       : Initializing JAAS config
run-mmm-kafdrop-1  | 2022-01-08 01:44:44.241  INFO ${sys:PID} [           main] k.Kafdrop$EnvironmentSetupListener       : env: null .isSecured kafka: false
run-mmm-kafdrop-1  | 2022-01-08 01:44:44.242  INFO ${sys:PID} [           main] k.Kafdrop$EnvironmentSetupListener       : Env: null
run-mmm-kafdrop-1  | 2022-01-08 01:44:44.434  INFO 1 [kground-preinit] o.h.v.i.u.Version                        : HV000001: Hibernate Validator 6.2.0.Final
run-mmm-kafdrop-1  | 2022-01-08 01:44:44.497  INFO 1 [           main] o.s.b.StartupInfoLogger                  : Starting application using Java 11.0.13 on 642a2b80108d with PID 1 (started by root in /)
run-mmm-kafdrop-1  | 2022-01-08 01:44:44.604  INFO 1 [           main] o.s.b.SpringApplication                  : No active profile set, falling back to default profiles: default
run-mmm-kafdrop-1  | 2022-01-08 01:44:47.864  INFO 1 [           main] i.u.s.s.ServletContextImpl               : Initializing Spring embedded WebApplicationContext
run-mmm-kafdrop-1  | 2022-01-08 01:44:47.864  INFO 1 [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 3184 ms
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.437  INFO 1 [           main] k.c.KafkaConfiguration                   : Checking truststore file kafka.truststore.jks
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.438  INFO 1 [           main] k.c.KafkaConfiguration                   : Checking keystore file kafka.keystore.jks
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.439  INFO 1 [           main] k.c.KafkaConfiguration                   : Checking properties file kafka.properties
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.584  WARN 1 [           main] o.a.k.c.ClientUtils                      : Couldn't resolve server kafka:9092 from bootstrap.servers as DNS resolution failed for kafka
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.589  WARN 1 [           main] o.s.c.s.AbstractApplicationContext       : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageInspector' defined in URL [jar:file:/kafdrop-3.28.0/kafdrop-3.28.0.jar!/BOOT-INF/classes!/kafdrop/service/MessageInspector.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kafkaMonitorImpl' defined in URL [jar:file:/kafdrop-3.28.0/kafdrop-3.28.0.jar!/BOOT-INF/classes!/kafdrop/service/KafkaMonitorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaHighLevelConsumer': Invocation of init method failed; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.680  INFO 1 [           main] ConditionEvaluationReportLoggingListener :
run-mmm-kafdrop-1  |
run-mmm-kafdrop-1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
run-mmm-kafdrop-1  | 2022-01-08 01:44:48.734 ERROR 1 [           main] o.s.b.SpringApplication                  : Application run failed
run-mmm-kafdrop-1  |
run-mmm-kafdrop-1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageInspector' defined in URL [jar:file:/kafdrop-3.28.0/kafdrop-3.28.0.jar!/BOOT-INF/classes!/kafdrop/service/MessageInspector.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kafkaMonitorImpl' defined in URL [jar:file:/kafdrop-3.28.0/kafdrop-3.28.0.jar!/BOOT-INF/classes!/kafdrop/service/KafkaMonitorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaHighLevelConsumer': Invocation of init method failed; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
run-mmm-kafdrop-1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
run-mmm-kafdrop-1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
run-mmm-kafdrop-1  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
run-mmm-kafdrop-1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
run-mmm-kafdrop-1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
run-mmm-kafdrop-1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
run-mmm-kafdrop-1  | 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
run-mmm-kafdrop-1  | 	at kafdrop.Kafdrop.main(Kafdrop.java:50)
run-mmm-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
run-mmm-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
run-mmm-kafdrop-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
run-mmm-kafdrop-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
run-mmm-kafdrop-1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
run-mmm-kafdrop-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
run-mmm-kafdrop-1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
run-mmm-kafdrop-1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
run-mmm-kafdrop-1  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'kafkaMonitorImpl' defined in URL [jar:file:/kafdrop-3.28.0/kafdrop-3.28.0.jar!/BOOT-INF/classes!/kafdrop/service/KafkaMonitorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaHighLevelConsumer': Invocation of init method failed; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
run-mmm-kafdrop-1  | 	... 26 more
run-mmm-kafdrop-1  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'kafkaHighLevelConsumer': Invocation of init method failed; nested exception is org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
run-mmm-kafdrop-1  | 	... 40 more
run-mmm-kafdrop-1  | Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:823)
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:664)
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:645)
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:625)
run-mmm-kafdrop-1  | 	at kafdrop.service.KafkaHighLevelConsumer.initializeClient(KafkaHighLevelConsumer.java:46)
run-mmm-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
run-mmm-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
run-mmm-kafdrop-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
run-mmm-kafdrop-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
run-mmm-kafdrop-1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
run-mmm-kafdrop-1  | 	... 53 more
run-mmm-kafdrop-1  | Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:88)
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:47)
run-mmm-kafdrop-1  | 	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:730)
run-mmm-kafdrop-1  | 	... 64 more
```

**Comment by haf** [comment]
Was missing `networks: ...`. Sorry, it's late.
