### ISSUE TITLE
Exceptions printed when used

### ISSUE THREAD

**Issue by haf** [obsidiandynamics/kafdrop#332]
```
run-mmm-kafdrop-1    | 2022-01-08 02:01:35.387 ERROR 1 [  XNIO-1 task-5] i.u.s.a.LoggingExceptionHandler          : UT005023: Exception handling request to /error
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | java.lang.RuntimeException: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
run-mmm-kafdrop-1    | ==> error.message  [in template "error.ftlh" at line 6, column 65]
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | Tip: It's the step after the last dot that caused this error, not those before it.
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | FTL stack trace ("~" means nesting-related):
run-mmm-kafdrop-1    | 	- Failed at: ${error.message}  [in template "error.ftlh" at line 6, column 63]
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | 	at io.undertow.servlet.spec.HttpServletResponseImpl.doErrorDispatch(HttpServletResponseImpl.java:167)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
run-mmm-kafdrop-1    | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
run-mmm-kafdrop-1    | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
run-mmm-kafdrop-1    | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
run-mmm-kafdrop-1    | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
run-mmm-kafdrop-1    | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
run-mmm-kafdrop-1    | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
run-mmm-kafdrop-1    | 	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
run-mmm-kafdrop-1    | 	at java.base/java.lang.Thread.run(Thread.java:829)
run-mmm-kafdrop-1    | Caused by: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
run-mmm-kafdrop-1    | ==> error.message  [in template "error.ftlh" at line 6, column 65]
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | Tip: It's the step after the last dot that caused this error, not those before it.
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | FTL stack trace ("~" means nesting-related):
run-mmm-kafdrop-1    | 	- Failed at: ${error.message}  [in template "error.ftlh" at line 6, column 63]
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
run-mmm-kafdrop-1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
run-mmm-kafdrop-1    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
run-mmm-kafdrop-1    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
run-mmm-kafdrop-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
run-mmm-kafdrop-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
run-mmm-kafdrop-1    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:102)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
run-mmm-kafdrop-1    | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
run-mmm-kafdrop-1    | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:257)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:182)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.spec.RequestDispatcherImpl.error(RequestDispatcherImpl.java:504)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.spec.RequestDispatcherImpl.error(RequestDispatcherImpl.java:417)
run-mmm-kafdrop-1    | 	at io.undertow.servlet.spec.HttpServletResponseImpl.doErrorDispatch(HttpServletResponseImpl.java:165)
run-mmm-kafdrop-1    | 	... 17 more
run-mmm-kafdrop-1    | Caused by: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
run-mmm-kafdrop-1    | ==> error.message  [in template "error.ftlh" at line 6, column 65]
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | Tip: It's the step after the last dot that caused this error, not those before it.
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | Tip: If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    |
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | FTL stack trace ("~" means nesting-related):
run-mmm-kafdrop-1    | 	- Failed at: ${error.message}  [in template "error.ftlh" at line 6, column 63]
run-mmm-kafdrop-1    | ----
run-mmm-kafdrop-1    | 	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
run-mmm-kafdrop-1    | 	at freemarker.core.EvalUtil.coerceModelToTextualCommon(EvalUtil.java:481)
run-mmm-kafdrop-1    | 	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:401)
run-mmm-kafdrop-1    | 	at freemarker.core.EvalUtil.coerceModelToStringOrMarkup(EvalUtil.java:370)
run-mmm-kafdrop-1    | 	at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:100)
run-mmm-kafdrop-1    | 	at freemarker.core.DollarVariable.accept(DollarVariable.java:63)
run-mmm-kafdrop-1    | 	at freemarker.core.Environment.visit(Environment.java:347)
run-mmm-kafdrop-1    | 	at freemarker.core.Environment.visit(Environment.java:353)
run-mmm-kafdrop-1    | 	at freemarker.core.Environment.process(Environment.java:326)
run-mmm-kafdrop-1    | 	at freemarker.template.Template.process(Template.java:383)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.processTemplate(FreeMarkerView.java:391)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.doRender(FreeMarkerView.java:304)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.view.freemarker.FreeMarkerView.renderMergedTemplateModel(FreeMarkerView.java:255)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.view.AbstractTemplateView.renderMergedOutputModel(AbstractTemplateView.java:179)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:316)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1401)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1145)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1084)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
run-mmm-kafdrop-1    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
run-mmm-kafdrop-1    | 	... 45 more
run-mmm-kafdrop-1    |

```

**Comment by bjornbouetsmith** [comment]
I can confirm - I get the exact same when trying to launch latest kafdrop in a docker container.

**Comment by davideicardi** [comment]
Which Kafdrop version are you using? Do you have any special configuration?

**Comment by haf** [comment]
latest

**Comment by claui** [comment]
> Which Kafdrop version are you using? Do you have any special configuration?

According to the log,
> `Kafdrop version: 3.28.0, build time: 2022-01-05T15:33:11.553Z`

**Comment by bjornbouetsmith** [comment]
I was using obsidiandynamics/kafdrop:latest as a docker image - when I reverted to obsidiandynamics/kafdrop:3.27.0 it started working.

**Comment by davideicardi** [comment]
It looks like an issue related to 
https://stackoverflow.com/questions/34352781/freemarker-nested-data-error-while-parsing

here
[A ${error.status} error has occurred: <span id="errorMessage">${error.message}</span>](https://github.com/obsidiandynamics/kafdrop/blob/29996f98e24ec5aff408e00c90c11c460271dafc/src/main/resources/templates/error.ftlh#L6)

What do you think?
Probably caused by the fact that we updated some libraries.

**Comment by claui** [comment]
@davideicardi Judging from the issue description:

> If the failing expression is known to legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??

and your observation:

> It looks like an issue related to
https://stackoverflow.com/questions/34352781/freemarker-nested-data-error-while-parsing

> here
A ${error.status} error has occurred: ${error.message}

chances are that the `.message` part in `${error.message}` resolves to null.
Have you tried replacing line 6 with the following?

```
A ${error.status} error has occurred:
<#if error.message??>
    <span id="errorMessage">${error.message}</span>
<#else>
</#if>
```

I’d try it myself and submit a PR, but I’ve been unable to get the Maven build working, no matter on which JDK version I try.

**Comment by davideicardi** [comment]
@claui Thank you for the suggestion. I suspect that the problem is in the model not in the view. So I suggest to fix it using PR #337 .

Also consider that I think the error was caused by the fact that at startup a `favicon` was requested by the browser, this generate a 404 error but the error page throw that exception.

What do you think?

**Comment by claui** [comment]
> I suspect that the problem is in the model not in the view. So I suggest to fix it using PR #337 .

Thank you @davideicardi. Sounds plausible!

I have only limited means to test right now as my Maven builds are failing (possibly for reasons unrelated to this project).
So I’ll have to wait for the next release that includes this fix in order to learn what the actual error is.

**Comment by vonBork** [comment]
@davideicardi Thanks for fixing the Bug with #337. Do you know when there will be a Release 3.28.1 or 3.29.0? Because of the Bug our Kafkdrop isn't usable at the moment and we can not go back to 3.27.0 because of the log4j issues.

Thanks in advance.

**Comment by davideicardi** [comment]
@vonBork @claui  If are using docker you can use `obsidiandynamics/kafdrop:3.29.0-SNAPSHOT`. We can probably create a new version soon, but if you can do some tests on the snapshot version it would be great! Because I didn't received much feedback for now...

**Comment by skroberto** [comment]
> If are using docker you can use `obsidiandynamics/kafdrop:3.29.0-SNAPSHOT`. We can probably create a new version soon, but if you can do some tests on the snapshot version it would be great! Because I didn't received much feedback for now...

@davideicardi I have just had the chance to test this. I was getting the same error above using `obsidiandynamics/kafdrop:latest` but it now works just fine using `obsidiandynamics/kafdrop:3.29.0-SNAPSHOT` as you suggested. Thanks!
