### ISSUE TITLE
 Connection to node -1 (kafka/172.18.0.2:29092) could not be established. Broker may not be available.

### ISSUE THREAD

**Issue by m-romandic-un1** [obsidiandynamics/kafdrop#352]
Machine using:
MacBook Pro M1 Pro

Steps to reproduce:

1. docker-compose/kafka-kafdrop/
2. `docker compose up`

`localkafka-kafdrop-1  | 2022-02-09 14:24:10.577  WARN 1 [| kafdrop-admin] o.a.k.c.NetworkClient                    : [AdminClient clientId=kafdrop-admin] Connection to node -1 (kafka/172.18.0.2:29092) could not be established. Broker may not be available.
`
Pinging to 127.0.0.1:9092 returns:
`ping: cannot resolve 127.0.0.1:9092: Unknown host`

And when I request localhost:9000 in browser after minute I get this error:

```
localkafka-kafdrop-1  | 2022-02-09 14:24:11.136 ERROR 1 [  XNIO-1 task-1] i.u.s.a.LoggingExceptionHandler          : UT005023: Exception handling request to /
localkafka-kafdrop-1  | 
localkafka-kafdrop-1  | org.springframework.web.util.NestedServletException: Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
localkafka-kafdrop-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
localkafka-kafdrop-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
localkafka-kafdrop-1  | 	at kafdrop.config.CorsConfiguration$1.doFilter(CorsConfiguration.java:89)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
localkafka-kafdrop-1  | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
localkafka-kafdrop-1  | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
localkafka-kafdrop-1  | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
localkafka-kafdrop-1  | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
localkafka-kafdrop-1  | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
localkafka-kafdrop-1  | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
localkafka-kafdrop-1  | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
localkafka-kafdrop-1  | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
localkafka-kafdrop-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
localkafka-kafdrop-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423)
localkafka-kafdrop-1  | 	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
localkafka-kafdrop-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
localkafka-kafdrop-1  | Caused by: kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | 	at kafdrop.service.KafkaHighLevelAdminClient.describeCluster(KafkaHighLevelAdminClient.java:66)
localkafka-kafdrop-1  | 	at kafdrop.service.KafkaMonitorImpl.getBrokers(KafkaMonitorImpl.java:53)
localkafka-kafdrop-1  | 	at kafdrop.controller.ClusterController.clusterInfo(ClusterController.java:70)
localkafka-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
localkafka-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
localkafka-kafdrop-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
localkafka-kafdrop-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
localkafka-kafdrop-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
localkafka-kafdrop-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
localkafka-kafdrop-1  | 	... 58 more
localkafka-kafdrop-1  | Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
localkafka-kafdrop-1  | 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
localkafka-kafdrop-1  | 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
localkafka-kafdrop-1  | 	at kafdrop.service.KafkaHighLevelAdminClient.describeCluster(KafkaHighLevelAdminClient.java:62)
localkafka-kafdrop-1  | 	... 73 more
localkafka-kafdrop-1  | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | 
localkafka-kafdrop-1  | 2022-02-09 14:24:11.173  INFO 1 [  XNIO-1 task-1] k.c.BasicErrorController                 : errorAtts: {timestamp=2022-02-09T14:24:11.170+0000, status=500, error=Internal Server Error, trace=kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | 	at kafdrop.service.KafkaHighLevelAdminClient.describeCluster(KafkaHighLevelAdminClient.java:66)
localkafka-kafdrop-1  | 	at kafdrop.service.KafkaMonitorImpl.getBrokers(KafkaMonitorImpl.java:53)
localkafka-kafdrop-1  | 	at kafdrop.controller.ClusterController.clusterInfo(ClusterController.java:70)
localkafka-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
localkafka-kafdrop-1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
localkafka-kafdrop-1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
localkafka-kafdrop-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
localkafka-kafdrop-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
localkafka-kafdrop-1  | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
localkafka-kafdrop-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497)
localkafka-kafdrop-1  | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
localkafka-kafdrop-1  | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
localkafka-kafdrop-1  | 	at kafdrop.config.CorsConfiguration$1.doFilter(CorsConfiguration.java:89)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
localkafka-kafdrop-1  | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
localkafka-kafdrop-1  | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
localkafka-kafdrop-1  | 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
localkafka-kafdrop-1  | 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
localkafka-kafdrop-1  | 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:275)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:79)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:134)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:131)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
localkafka-kafdrop-1  | 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:255)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:79)
localkafka-kafdrop-1  | 	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:100)
localkafka-kafdrop-1  | 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
localkafka-kafdrop-1  | 	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:852)
localkafka-kafdrop-1  | 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
localkafka-kafdrop-1  | 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
localkafka-kafdrop-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
localkafka-kafdrop-1  | 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1423)
localkafka-kafdrop-1  | 	at org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
localkafka-kafdrop-1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
localkafka-kafdrop-1  | Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
localkafka-kafdrop-1  | 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
localkafka-kafdrop-1  | 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
localkafka-kafdrop-1  | 	at kafdrop.service.KafkaHighLevelAdminClient.describeCluster(KafkaHighLevelAdminClient.java:62)
localkafka-kafdrop-1  | 	... 73 more
localkafka-kafdrop-1  | Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
localkafka-kafdrop-1  | , message=Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes, path=/}

```

**Comment by OneCricketeer** [comment]
1. You cannot ping a port
2. Pinging 127.0.0.1 is the kafdrop container (or your mac), not the Kafka container
3. Does `docker compose up kafka` work on its own? Does that container support ARM runtime?

**Comment by m-romandic-un1** [comment]
127.0.0.1 is my Mac, from my mac I am trying to ping exposed port from Kafka service. Checked it, it does not work. How can I check does it support?

**Comment by OneCricketeer** [comment]
Again, `ping` does not check ports. `nc` command does.

Better option from the Mac, you would be to install `kcat` (through brew) and use `kcat -L -b localhost:9092` to check that the port is open and the listeners are set correctly.  

 **However**, that still wouldn't verify if `kafdrop` can itself connect to the Kafka container. 

> How can I check does it support?

As shown on Docker Hub, only amd64, not arm is supported - https://hub.docker.com/r/obsidiandynamics/kafka/tags 

You'll need to use a different container for Kafka (and Zookeeper) for running against with an M1 ARM machine if you are not otherwise emulating an AMD64 environment

[Read Docker docs](https://docs.docker.com/desktop/mac/apple-silicon/) ... 
> Not all images are available for ARM64 architecture. You can add `--platform linux/amd64` to run an Intel image under emulation

Related https://github.com/obsidiandynamics/kafdrop/issues/302

**Comment by altaiezior** [comment]
@OneCricketeer if you want to try I have a fork https://github.com/arm64-compat/kafdrop/pkgs/container/kafdrop which supports arm compatible image.

Note that the image is not production compatible, only for local development if you own M1
