### ISSUE TITLE
Request processing failed, NPE in KafkaConfiguration.applyCommon

### ISSUE THREAD

**Issue by jmgomez77** [obsidiandynamics/kafdrop#362]
2022-03-20 16:59:51.077 ERROR 17632 --- [nio-9000-exec-3] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
        at java.util.Hashtable.put(Hashtable.java:460) ~[?:1.8.0_322]
        at java.util.Properties.setProperty(Properties.java:166) ~[?:1.8.0_322]
        at com.homeadvisor.kafdrop.config.KafkaConfiguration.applyCommon(KafkaConfiguration.java:134) ~[classes!/:?]
        at com.homeadvisor.kafdrop.service.ClientKafkaMonitor$AdminClientObjectFactory.create(ClientKafkaMonitor.java:565) ~[classes!/:?]
        at com.homeadvisor.kafdrop.service.ClientKafkaMonitor$AdminClientObjectFactory.create(ClientKafkaMonitor.java:552) ~[classes!/:?]

**Comment by davideicardi** [comment]
Can you provide some more info:
- Kafdrop version
- configuration
- when do you see the error?
