### ISSUE TITLE
Old version Kafka  compatibility problem

### ISSUE THREAD

**Issue by zihengCat** [obsidiandynamics/kafdrop#53]
Hey guys, does *Kafdrop* support old version `Kafka 0.10.1.0` ?

The requirements says Kafdrop support Kafka (version 0.10.0 or newer), I tested with compiled `kafdrop-3.19.0-SNAPSHOT.jar`, it seems unsupported (`UnsupportedVersionException` occured )...

Is there any way to let Kafdrop be compatible with old version Kafka ? Something like setting `zookeeper` configurations ?

```plain
...
org.springframework.web.util.NestedServletException: Request processing failed; nested exception is kafdrop.service.KafkaAdminClientException: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support DESCRIBE_CONFIGS
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1013)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at kafdrop.config.CorsConfiguration$1.doFilter(CorsConfiguration.java:88)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        ...
```

- OS: *`CentOS 7 Linux Kernel 3.10.0-514.16.1.el7.x86_64`*
- JDK: *`OpenJDK 13.0.1-b9`*

**Comment by ekoutanov** [comment]
Yes I think you're right. We added `DESCRIBE_CONFIGS` admin operation not too long ago, and 0.10.0 doesn't support it.
I need to do a compatibility check on older brokers to update the readme. But to be honest, the intention of Kafdrop is not to offer extensive backward compatibility for versions that are several years old now, but to keep to sacrifice _some_ compatibility for functionality. This is also why we dropped ZooKeeper support. 
If you absolutely need this (i.e. you can't upgrade your brokers), consider catching the `UnsupportedVersionException` exception and returning an empty set of configs. You can fork it and put in a pull request.

**Comment by zihengCat** [comment]
@ekoutanov  

Got it, the implementation of service use a Kafka `AdminClient`, which was introduced in `0.11.0.0`.
 
`README.md` should be updated to make it more clearly.

<img width="1548" alt="Screen Shot 2019-12-06 at 12 06 10" src="https://user-images.githubusercontent.com/19472493/70295127-cddc2c00-1820-11ea-8460-844740177628.png">
