### ISSUE TITLE
Not able to connect to MSK cluster using SASL

### ISSUE THREAD

**Issue by khamkarp** [obsidiandynamics/kafdrop#663]
We are following documentation for connecting to MSK cluster using SASL by adding aws-msk-iam-auth-1.0.0.jar file in extra-kafdrop-classes folder.

We are trying to run kafdropui container on docker host network to connect to MSK cluster but its failing with below error.

Please help us to resolve this  issue.

```
rror starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-07-16 08:59:43.886 ERROR 1 [           main] o.s.b.SpringApplication                  : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consumerController' defined in URL [jar:nested:/kafdrop-4.0.2/kafdrop-4.0.2.jar/!BOOT-INF/classes/!/kafdrop/controller/ConsumerController.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'kafkaMonitorImpl' defined in URL [jar:nested:/kafdrop-4.0.2/kafdrop-4.0.2.jar/!BOOT-INF/classes/!/kafdrop/service/KafkaMonitorImpl.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'kafkaHighLevelConsumer': Invocation of init method failed
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1357)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1194)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
```

**Comment by Preethi-KRP** [comment]
I am getting the same error. How was this issue fixed?
