### ISSUE TITLE
help with kafdrop stackoverflow error

### ISSUE THREAD

**Issue by erjan** [obsidiandynamics/kafdrop#702]
from docker-compose: 

```
docker-compose logs kafdrop
Attaching to kafdrop
kafdrop      | 
kafdrop      | :::    :::     :::     :::::::::: :::::::::  :::::::::   ::::::::  :::::::::           :::    
kafdrop      | :+:   :+:    :+: :+:   :+:        :+:    :+: :+:    :+: :+:    :+: :+:    :+:         :+:     
kafdrop      | +:+  +:+    +:+   +:+  +:+        +:+    +:+ +:+    +:+ +:+    +:+ +:+    +:+        +:+ +:+  
kafdrop      | +#++:++    +#++:++#++: :#::+::#   +#+    +:+ +#++:++#:  +#+    +:+ +#++:++#+        +#+  +:+  
kafdrop      | +#+  +#+   +#+     +#+ +#+        +#+    +#+ +#+    +#+ +#+    +#+ +#+             +#+#+#+#+#+
kafdrop      | #+#   #+#  #+#     #+# #+#        #+#    #+# #+#    #+# #+#    #+# #+#                   #+#  
kafdrop      | ###    ### ###     ### ###        #########  ###    ###  ########  ###                   ###  
kafdrop      | 
kafdrop      | OpenJDK 64-Bit Server VM warning: Options -Xverify:none and -noverify were deprecated in JDK 13 and will likely be removed in a future release.
kafdrop      | 2024-11-24 19:31:48.371  INFO ${sys:PID} [           main] k.Kafdrop$EnvironmentSetupListener       : Initializing JAAS config
kafdrop      | 2024-11-24 19:31:48.457  INFO ${sys:PID} [           main] k.Kafdrop$EnvironmentSetupListener       : Env: null
kafdrop      | 2024-11-24 19:31:49.168  INFO 1 [kground-preinit] o.h.v.i.u.Version                        : HV000001: Hibernate Validator 8.0.1.Final
kafdrop      | 2024-11-24 19:31:49.434  INFO 1 [           main] o.s.b.StartupInfoLogger                  : Starting Kafdrop v4.0.2 using Java 17.0.11 with PID 1 (/kafdrop-4.0.2/kafdrop-4.0.2.jar started by root in /)
kafdrop      | 2024-11-24 19:31:49.458  INFO 1 [           main] o.s.b.SpringApplication                  : No active profile set, falling back to 1 default profile: "default"
kafdrop      | 2024-11-24 19:31:55.540  WARN 1 [           main] o.s.c.s.AbstractApplicationContext       : Exception encountered during context initialization - cancelling refresh attempt: java.lang.StackOverflowError
kafdrop      | 2024-11-24 19:31:55.606  INFO 1 [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
kafdrop      | 
kafdrop      | Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
kafdrop      | 2024-11-24 19:31:55.672 ERROR 1 [           main] o.s.b.SpringApplication                  : Application run failed
kafdrop      | 
kafdrop      | java.lang.StackOverflowError
kafdrop      |  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
kafdrop      |  at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
kafdrop      |  at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
kafdrop      |  at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
kafdrop      |  at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
kafdrop      |  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
kafdrop      |  at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
kafdrop      |  at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
kafdrop      |  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
kafdrop      |  at java.base/java.lang.ClassLoader.defineClass1(Native Method)
```

what is the reason for fail?

**Comment by azitmentor** [comment]
i had the same issue, just remove the JVM_OPTS from the compose file, or set the -Xss300K  options to 300k (not a java expert, i assume stack size)
